site_name: StockLab
site_url: https://zju-se-stocklab.github.io/docs/
site_author: Team C

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme: light)'
      primary: deep-purple
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: '(prefers-color-scheme: dark)'
      primary: deep-purple
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  language: zh
  font:
    code: JetBrains Mono
  features:
    - content.code.copy
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    # - toc.integrate
    - header.autohide
  icon:
    repo: fontawesome/brands/git-alt

plugins:
  - search
  # - heti:
  #     disable_serve: false
repo_url: https://github.com/ZJU-SE-StockLab
repo_name: StockLab

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - _css/style.css
  - _css/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/tex-mml-chtml.js

nav:
  - Home:
      - 主页: index.md
      - background.md
  - API:
      - 上手指南: api/index.md
  - Client:
      - 上手指南: client/index.md
  - Server:
      - 上手指南: server/index.md
